#version 450

layout (local_size_x = 16, local_size_y = 16) in;

layout(set = 0, binding = 0) uniform sampler2D t_input;
layout(set = 1, binding = 1, rgba8) uniform writeonly image2D t_output;

void main()
{
    const ivec2 resolution = imageSize(t_output);
    const vec2 uv = (vec2(gl_GlobalInvocationID.xy + 0.5f) / resolution);

    vec3 rgb = texture(t_input, uv).rgb;
    imageStore(t_output, ivec2(gl_GlobalInvocationID.xy), vec4(rgb, 1));
}
